baseURL = 'https://healthhatch.co/'
languageCode = 'zh-HK'
title = 'HealthHatch Blog'

defaultContentLanguage = 'zh-HK'
defaultContentLanguageInSubdir = false

[languages]
  [languages.zh-HK]
    languageName = '繁體中文'
    weight = 1
    title = 'HealthHatch'
    contentDir = 'content/zh-hk'
    
  [languages.en]
    languageName = 'English'
    weight = 2
    title = 'HealthHatch Blog'
    contentDir = 'content/en'

[menu]
  [[menu.main]]
    identifier = 'about'
    name = '關於我們'
    url = '/about/'
    weight = 1
  [[menu.main]]
    identifier = 'services'
    name = '我們的服務'
    url = '/services/'
    weight = 2
  [[menu.main]]
    identifier = 'individual'
    name = '個人服務'
    url = '/individual-services/'
    weight = 3
  [[menu.main]]
    identifier = 'enterprise'
    name = '企業方案'
    url = '/enterprise-solutions/'
    weight = 4
  [[menu.main]]
    identifier = 'consultation'
    name = '健康諮詢'
    url = '/consultation/'
    weight = 5
  [[menu.main]]
    identifier = 'posts'
    name = '最新消息'
    url = '/posts/'
    weight = 6

[[languages.zh-HK.menu.main]]
  identifier = 'about'
  name = '關於我們'
  url = '/about/'
  weight = 1
[[languages.zh-HK.menu.main]]
  identifier = 'services'
  name = '我們的服務'
  url = '/services/'
  weight = 2
[[languages.zh-HK.menu.main]]
  identifier = 'individual'
  name = '個人服務'
  url = '/individual-services/'
  weight = 3
[[languages.zh-HK.menu.main]]
  identifier = 'enterprise'
  name = '企業方案'
  url = '/enterprise-solutions/'
  weight = 4
[[languages.zh-HK.menu.main]]
  identifier = 'consultation'
  name = '健康諮詢'
  url = '/consultation/'
  weight = 5
[[languages.zh-HK.menu.main]]
  identifier = 'posts'
  name = '最新消息'
  url = '/posts/'
  weight = 6

[[languages.en.menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/en/'
  weight = 1
[[languages.en.menu.main]]
  identifier = 'posts'
  name = 'Posts'
  url = '/en/posts/'
  weight = 2

[params]
  featured_image = '/images/default-featured.jpg'
  author = 'HealthHatch Team'
  description = 'HealthHatch Blog - 健康資訊與最新消息'
  show_recent_posts = true

